#!/bin/bash

BR2_ROOT=$(pwd)
PKG_NAME=uboot_ubmc
PKG_VERSION=custom
PKG_TAR_NAME=u-boot-2017.01+gitAUTOINC+590c7d7fe1-g590c7d7fe1.tar.gz
PKG_DIR_NAME=uboot-${PKG_VERSION}

PATCH_LOCATION=${BR2_ROOT}/ti/uboot-patches

PATCH_NAME_MAIN=uboot-0001-main.patch
PATCH_MAIN_EXCEPT_FILE=files_uboot_ubmc_main_exc.txt

PATCH_NAME[1]=uboot-0002-eclipse_proj.patch
PATCH_FLIST[1]=files_eclipse.txt

PATCH_NAME[2]=uboot-0003-boot_fix.patch
PATCH_FLIST[2]=files_uboot_boot_fix.txt

PATCH_NAME[3]=uboot-0004-board_ubmc.patch
PATCH_FLIST[3]=files_uboot_board_ubmc.txt

PATCH_NAME[4]=uboot-0005-board_myir.patch
PATCH_FLIST[4]=files_uboot_board_myir.txt

PATCH_NAME[5]=uboot-0006-mtest.patch
PATCH_FLIST[5]=files_uboot_memtest.txt

PATCH_NAME[6]=uboot-0007-ext4_fix.patch
PATCH_FLIST[6]=files_uboot_ext4_fix.txt

PATCH_NAME[7]=uboot-0008-config.patch
PATCH_FLIST[7]=files_uboot_config.txt

PATCH_NAME[8]=uboot-0009-dts.patch
PATCH_FLIST[8]=files_uboot_dts.txt

PATCH_NAME[9]=uboot-0010-board_ubmc_eval.patch
PATCH_FLIST[9]=files_uboot_board_ubmc_eval.txt

PATCH_NAME[10]=uboot-0011-eth_fix.patch
PATCH_FLIST[10]=files_eth_fix.txt

PATCH_GEN_REQ_CLEAN=0
PATCH_GEN_REQ_DIST_CLEAN=1


