#!/bin/bash

PKG_NAME=libnetconf
PKG_VERSION=master
PKG_TAR_NAME=libnetconf-master.tar.gz
PKG_DIR_NAME=${PKG_NAME}-${PKG_VERSION}

PATCH_LOCATION=${BR2_ROOT}/../base/package/${PKG_NAME}
PKG_PRE_PATCH_DIR=${PATCH_LOCATION}

PATCH_NAME_MAIN=
PATCH_MAIN_EXCEPT_FILE=

PATCH_NAME[1]=0100-fix-configure.patch
PATCH_FLIST[1]=files_libnetconf_configure.txt

#PATCH_GEN_REQ_CLEAN=1



