/* this file is created by silc_cli_inst_code_gen.py */ 

#include "silc_mgmtd_interface.h"
#include "silc_cli_terminal.h"
#include "silc_cli_error.h"
#include "silc_cli_common.h"
#include "silc_cli_types.h"

int is_cli_cmd_show_file(silc_cstr filename);

int is_cli_cmd_reboot();

int is_cli_cmd_config_mgmt_get_dft_filename(char* str, int len)
{
	time_t t;
	struct tm tm;

	t = time(NULL);
	localtime_r(&t, &tm);
	strftime(str, len, "is_config_%Y%m%d%H%M%S", &tm);
	return 0;
}

int is_cli_cmd_check_config_filename(silc_cstr name)
{
	int loop, len = strlen(name);
	char path[256];

	for(loop=0; loop<len; loop++)
	{
		if((name[loop] >= 'a' && name[loop] <= 'z') ||
				(name[loop] >= 'A' && name[loop] <= 'Z') ||
				(name[loop] >= '0' && name[loop] <= '9') ||
					name[loop] == '.' ||
					name[loop] == '_' ||
					name[loop] == '-')
			continue;
		else
		{
			silc_cli_print("%% Invalid file name '%c', only support [a~z][A~Z][0~9][._-].\n", name[loop]);
			return -1;
		}
	}
#ifndef SILC_MGMTD_LOCAL_DEBUG
	sprintf(path, "/config/extend/%s", name);
#else
	sprintf(path, "./extend/%s", name);
#endif
	if(access(path, F_OK) == 0)
	{
		return silc_cli_cmd_confirm("%% The configuration is exist, Overwrite (y|n) ?", NULL, "%% Cancelled");
	}
	return 0;
}

int is_cli_cmd_check_config_file(silc_cstr filename)
{
	int len = 100;
	char buf[len];
	char cmd[200];

	sprintf(cmd, "is_check_conf.sh %s", filename);
	if(silc_mgmtd_if_exec_system_cmd(cmd, buf, &len, 1000, silc_false) != 0 || strncmp(buf, "OK", 2) != 0)
	{
		silc_cli_err_cmd_set_err_info("Please upload a valid configuration file, which should be generated by the device and not modified manually!");
		return -1;
	}
	return 0;
}

int is_cli_cmd_config_mgmt_get_req_info(silc_list* p_token_list, is_cli_cmd_req_info* p_req_info, silc_bool* reboot)
{
	silc_cli_token *p_token;
	static char filename[256];
	char tmpfile[256];
	silc_cstr url = NULL;

	p_req_info->root_val = NULL;
	p_req_info->type = SILC_MGMTD_IF_REQ_ACTION;
	silc_list_for_each_entry(p_token, p_token_list, rl_node)
	{
		if(strcmp(p_token->name, "save") == 0)
		{
			sprintf(p_req_info->path, "/action/system/save-config-as");
		}
		else if(strcmp(p_token->name, "upload") == 0)
		{
			url = p_token->val_str;
		}
		else if(strcmp(p_token->name, "as") == 0)
		{
			if(is_cli_cmd_check_config_filename(p_token->val_str) != 0)
			{
				p_req_info->path[0] = 0;
				return 0;
			}
			p_req_info->root_val = p_token->val_str;
		}
		else if(strcmp(p_token->name, "restore") == 0)
		{
			char filename[256];
			sprintf(filename, "/config/extend/%s", p_token->val_str);
			silc_cli_print("The configuration to be restored is as below:\n\n");
			is_cli_cmd_show_file(filename);
			silc_cli_print("\n");
			if (0 != silc_cli_cmd_confirm("%% Warning: Current configuration will be overwritten and the device will be rebooted! Continue (y|n) ?", NULL, "%% Cancelled"))
				return 0;
			sprintf(p_req_info->path, "/action/system/load-config-from");
			p_req_info->root_val = p_token->val_str;
			*reboot = silc_true;
			return 0;
		}
		else if(strcmp(p_token->name, "reset") == 0)
		{
			if (0 != silc_cli_cmd_confirm("%% Warning: Current configuration will be lost and the device will be rebooted! Continue (y|n) ?", NULL, "%% Cancelled"))
				return 0;
			sprintf(p_req_info->path, "/action/system/load-default-config");
			p_req_info->root_val = "";
			*reboot = silc_true;
			return 0;
		}
	}
	if (!p_req_info->root_val)
	{
		is_cli_cmd_config_mgmt_get_dft_filename(filename, 256);
		p_req_info->root_val = filename;
	}
	if (!url)
		return 0;

	sprintf(tmpfile, "/tmp/is_config_%u.tmp", (uint32_t)time(NULL));
	if(silc_cli_upload_file(url, NULL, NULL, tmpfile) != 0)
		return -1;
	if (is_cli_cmd_check_config_file(tmpfile) != 0)
	{
		unlink(tmpfile);
		return -1;
	}
	else
	{
		char cmd[512];
		// here we should call a script to process the uploaded file
		snprintf(cmd, 512, "sudo mv %s /config/extend/%s", tmpfile, p_req_info->root_val);
		system(cmd);
	}

	return 0;
}

int is_cli_cmd_config_mgmt(silc_list* p_token_list)
{
	is_cli_cmd_req_info req_info;
	silc_bool reboot = silc_false;

	memset(&req_info, 0, sizeof(req_info));
	if(is_cli_cmd_config_mgmt_get_req_info(p_token_list, &req_info, &reboot) != 0)
		return -1;

	if(strlen(req_info.path) == 0)
	{
		return 0;
	}

	if(is_cli_cmd_do_request(&req_info, p_token_list) != 0)
		return -1;

	if (reboot)
		return is_cli_cmd_reboot();
    return 0;
}

