language: c
compiler:
  - gcc
before_script:
  - ./configure --enable-werror
before_install:
  - sudo apt-get update -qq
  - >
       sudo apt-get install --no-install-recommends -qq
       autoconf
       build-essential
       libpam0g-dev
script: make
