#!/bin/bash

PKG_NAME=openssh
PKG_VERSION=6.7p1
PKG_TAR_NAME=openssh-6.7p1.tar.gz
PKG_DIR_NAME=${PKG_NAME}-${PKG_VERSION}

PATCH_LOCATION=${BR2_ROOT}/package/${PKG_NAME}
PKG_PRE_PATCH_DIR=${PATCH_LOCATION}

PATCH_NAME_MAIN=
PATCH_MAIN_EXCEPT_FILE=

PATCH_NAME[1]=0100-eclipse-proj.patch
PATCH_FLIST[1]=files_eclipse.txt

PATCH_NAME[2]=0101-fix-pam-remote-auth.patch
PATCH_FLIST[2]=files_openssh_pam_fix.txt

#PATCH_GEN_REQ_CLEAN=1



