#!/bin/sh
#
# Start/stop is_web
#

case "$1" in
  start)
        echo "Starting is_web..."
        /opt/silc-web/silc-web-start.sh &
        ;;
  stop)
        echo "Stopping is_web..."
        #ps -ef|grep is_web|grep -v "grep"|awk '{print $1}'|xargs kill
        killall uhttpd
        ;;
  restart|reload)
        "$0" stop
        "$0" start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

