
#ifndef SILC_MGMTD_LIB_ERR_H_
#define SILC_MGMTD_LIB_ERR_H_

#include "silc_common.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef enum
{
	LIB_ERR_NULL = 0,
	LIB_ERR_SYS_OUT_OF_MEM,
	LIB_ERR_SYS_CLIB,	// C libaray error, use errno

	LIB_ERR_VAR_TYPE_NAME_INVALID,
	LIB_ERR_VAR_TYPE_UNKNOWN,
	LIB_ERR_VAR_VAL_TOSTR_FAILED,
	LIB_ERR_VAR_VAL_BUFF_NOT_ENOUGH,
	LIB_ERR_VAR_INVALID_VAL_STR,
	LIB_ERR_VAR_VAL_OUTOFRANGE,

	LIB_ERR_CONN_TIMED_OUT,
	LIB_ERR_CONN_CLOSED,
	LIB_ERR_CONN_READ_EAGAIN,
	LIB_ERR_CONN_IS_NOTEXIST,
	LIB_ERR_CONN_ID_IS_NULL,
	LIB_ERR_CONN_POP_DATA_FAILED,
	LIB_ERR_CONN_SOCK_CREATE_FAILED,
	LIB_ERR_CONN_CONNECT_TIMEOUT,
	LIB_ERR_CONN_SEND_FAILED,

	LIB_ERR_IF_NODE_NOTEXIST,
	LIB_ERR_IF_NODE_TRAVERSAL_CB_FAILED,
	LIB_ERR_IF_NODE_PATH_NOTEXIST,
	LIB_ERR_IF_REQ_TYPE_UNKNOWN,
	LIB_ERR_IF_REQ_BUFF_NOTENOUGH,
	LIB_ERR_IF_MSG_STR_INVALID,
	LIB_ERR_IF_MSG_SEQ_STR_INVALID,
	LIB_ERR_IF_MSG_HEAD_NOTEXIST,
	LIB_ERR_IF_MSG_END_NOTEXIST,
	LIB_ERR_IF_MSG_ITEM_HEAD_NOTEXIST,
	LIB_ERR_IF_MSG_IS_EMPTY,
	LIB_ERR_IF_MSG_WAIT_TIMEOUT,
	LIB_ERR_IF_MSG_WRONG_SEQNUM,
	LIB_ERR_IF_EXEC_SYSCMD_TIMEOUT,
	LIB_ERR_IF_SET_LOGIN_INFO_FAILED,
	LIB_ERR_IF_GET_IDLE_TIMEOUT_FAILED,
	LIB_ERR_IF_SET_NOTIFY_PATH_FAILED,
	LIB_ERR_IF_NOT_ENOUGH_NOTIFY_PATH,


	LIB_ERR_MAX,
}silc_mgmtd_lib_err;

silc_cstr silc_mgmtd_lib_err_str(void);

void silc_mgmtd_lib_err_set(silc_mgmtd_lib_err err);


#ifdef __cplusplus
}
#endif

#endif /* SILC_MGMTD_LIB_ERR_H_ */
