#!/bin/sh

#/usr/sbin/load_bcm
#/usr/sbin/is_mount_flash.sh
#/usr/sbin/is_upgrade.sh -C
#/usr/sbin/is_version_hack.sh

echo "1" > /proc/sys/kernel/sysrq

echo "Staring services"
# Start all init scripts in /etc/init.d
# executing them in numerical order.
#
for i in /etc/init.d/S??* ;do
  # Ignore dangling symlinks (if any).
  [ ! -f "$i" ] && continue

  case "$i" in
  *.sh)
    # Source shell script for speed.
    (
      trap - INT QUIT TSTP
      set start
      . $i
    )
    ;;
  *)
    # No sh extension, so fork subprocess.
    $i start
    ;;
  esac
done
/bin/sh

