/* this file is created by silc_cli_inst_code_gen.py */ 

#include "silc_common.h"
#include "silc_mgmtd_interface.h"
#include "is_cli_func.h"
#include <dlfcn.h>


/* define initialize structure */
typedef struct silc_cli_mode_info_s
{
    silc_cstr name;
    silc_cstr prompt;
}silc_cli_mode_info;

/* define initialize info */ 
// mode
static silc_cli_mode_info s_silc_cli_mode_info_list[] = {
{"user_exec", "> "},
{"privileged_exec", "# "},
{"configure", "(config)# "},
};

// token
static silc_cli_token_info s_silc_cli_token_info_list[] = {
{"user_exec cli", "Configure CLI shell options", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, is_cli_cmd_cli_config, NULL, 0, 0, 0},
{"user_exec cli clear-history", "Clear the CLI command history for the current user", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"user_exec enable", "Enter enable mode", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, is_cli_cmd_enable_go, NULL, 0, 0, 0},
{"user_exec exit", "Log out of the CLI", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, is_cli_cmd_exit_go, NULL, 0, 0, 0},
{"user_exec help", "View description of the interactive help system", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, is_cli_cmd_help_do, NULL, 0, 0, 0},
{"user_exec show", "Display system configuration or statistics", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, is_cli_cmd_show_do, NULL, 0, 0, 0},
{"user_exec show cli", "Display CLI options", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"user_exec show clock", "Display system date and time", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"user_exec show com", "Display serial console configuration", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"user_exec show com configured", "Display serial console configuration", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"user_exec show management", "Display system management configuration and state", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"user_exec show management configured", "Display system management configuration", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"user_exec show management state", "Display system management state", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"user_exec show name", "Display device name configuration", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"user_exec show name configured", "Display device name configuration", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"user_exec show session", "Display session runtime state", "", NULL, NULL, TOKEN_MODE_OPTIONAL, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"user_exec show session configured", "Display session configuration", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"user_exec show users", "Display a list of user accounts", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"user_exec show version", "Display version information for current system image", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},

{"privileged_exec clear", "Reset certain statistics or clear caches", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, is_cli_cmd_clear_go, NULL, 0, 0, 0},
{"privileged_exec clear event", "Clear system events", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"privileged_exec cli", "Configure CLI shell options", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, is_cli_cmd_cli_config, NULL, 0, 0, 0},
{"privileged_exec cli clear-history", "Clear the CLI command history for the current user", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"privileged_exec configure", "Enter configuration mode", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, is_cli_cmd_config_go, NULL, 0, 0, 0},
{"privileged_exec clock", "Set the system clock", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, is_cli_cmd_clock_config, NULL, 0, 0, 0},
{"privileged_exec clock set", "Set the time or date", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"privileged_exec clock set date", "Set the system date", "YYYY-MM-DD", "set-date", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"privileged_exec clock set time", "Set the system time", "hh:mm:ss", "set-time", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"privileged_exec disable", "Leave enable mode", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, is_cli_cmd_disable_go, NULL, 0, 0, 0},
{"privileged_exec exit", "Log out of the CLI", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, is_cli_cmd_exit_go, NULL, 0, 0, 0},
{"privileged_exec help", "View description of the interactive help system", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, is_cli_cmd_help_do, NULL, 0, 0, 0},
{"privileged_exec show", "Display system configuration or statistics", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, is_cli_cmd_show_do, NULL, 0, 0, 0},
{"privileged_exec show cli", "Display CLI options", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"privileged_exec show clock", "Display system time and date", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"privileged_exec show com", "Display serial console configuration", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"privileged_exec show com configured", "Display serial console configuration", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"privileged_exec show cpu", "Display CPU usage", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"privileged_exec show log", "Display log or its configuration", "", NULL, NULL, TOKEN_MODE_OPTIONAL, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"privileged_exec show log filter", "Display log with filter", "filter keyword", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"privileged_exec show log realtime", "Display realtime log", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"privileged_exec show log configured", "Display log configuration", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"privileged_exec show management", "Display system management configuration and state", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"privileged_exec show management configured", "Display system management configuration", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"privileged_exec show management state", "Display system management state", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"privileged_exec show memory", "Display system memory usage", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"privileged_exec show name", "Display device name configuration", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"privileged_exec show name configured", "Display device name configuration", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"privileged_exec show ntp", "Display NTP runtime state", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"privileged_exec show ntp configured", "Display NTP configuration", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"privileged_exec show radius", "Display RADIUS configuration", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"privileged_exec show radius configured", "Display RADIUS configuration", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"privileged_exec show session", "Display session runtime state", "", NULL, NULL, TOKEN_MODE_OPTIONAL, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"privileged_exec show session configured", "Display session configuration", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"privileged_exec show snmp", "Display SNMP runtime state", "", NULL, NULL, TOKEN_MODE_OPTIONAL, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"privileged_exec show snmp configured", "Display SNMP configuration", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"privileged_exec show snmp engineID", "Display SNMP engine ID of the local system", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"privileged_exec show ssh", "Display SSH runtime state", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"privileged_exec show ssh configured", "Display SSH configuration", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"privileged_exec show storage", "Display storage usage", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"privileged_exec show tacacs", "Display TACACS+ configuration", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"privileged_exec show tacacs configured", "Display TACACS+ configuration", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"privileged_exec show users", "Display a list of user accounts", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"privileged_exec show version", "Display version information for current system image", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"privileged_exec show web", "Display web runtime state", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"privileged_exec show web configured", "Display web configuration", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"privileged_exec reload", "Reboot the system", "", NULL, NULL, TOKEN_MODE_OPTIONAL, TOKEN_TYPE_STATIC, is_cli_cmd_reload_go, NULL, 0, 0, 0},
{"privileged_exec reload force", "Force an immediate reboot of the system even if it's busy", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"privileged_exec reload noconfirm", "Reboot the system without asking about unsaved changes", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"privileged_exec write", "Save the running configuration to persistent storage", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, is_cli_cmd_write_go, NULL, 0, 0, 0},
{"privileged_exec write memory", "Save running configuration to the active configuration file", "", "save-config", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},

{"configure clear", "Reset certain statistics or states", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, is_cli_cmd_clear_go, NULL, 0, 0, 0},
{"configure clear event", "Clear system events", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure cli", "Configure CLI shell options", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, is_cli_cmd_cli_config, NULL, 0, 0, 0},
{"configure cli clear-history", "Clear the CLI command history for the current user", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure clock", "Configure the system clock or timezone", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, is_cli_cmd_clock_config, NULL, 0, 0, 0},
{"configure clock set", "Set the time or date", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure clock set date", "Set the system date", "YYYY-MM-DD", "set-date", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure clock set time", "Set the system time", "hh:mm:ss", "set-time", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure clock timezone", "Set the system time zone", "", "timezone", NULL, TOKEN_MODE_OPTIONAL, TOKEN_TYPE_DYNAMIC, NULL, is_cli_dync_get_tz_group, 4096, 0, 0},
{"configure clock timezone area", "Set the system time zone area", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_DYNAMIC, NULL, is_cli_dync_get_timezone, 4096, 2, 0},
{"configure com", "Configure serial console", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, is_cli_cmd_service_config, NULL, 0, 0, 0},
{"configure com speed", "Configure serial console speed", "", "speed", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure com speed 9600", "Set speed 9600", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure com speed 38400", "Set speed 38400", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure com speed 115200", "Set speed 115200", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure com terminal-type", "Configure serial console terminal type", "terminal type, such as vt100", "termtype", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure configurations", "Manage system configuration files", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, is_cli_cmd_config_mgmt, NULL, 0, 0, 0},
{"configure configurations save", "Save current configuration to a file with default name is_config_yyyymmddHHMMSS", "", NULL, NULL, TOKEN_MODE_OPTIONAL, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure configurations save as", "Save current configuration as given name", "filename", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_DYNAMIC, NULL, is_cli_dync_get_config_list, 2048, 0, 0},
{"configure configurations upload", "Upload a configuration file, default name is_config_yyyymmddHHMMSS", "url such as http://xxx/file or scp://xxx@x.x.x.x:/path/file", NULL, NULL, TOKEN_MODE_OPTIONAL, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure configurations upload as", "Upload a configuration file as given name", "filename", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_DYNAMIC, NULL, is_cli_dync_get_config_list, 2048, 0, 0},
{"configure configurations restore", "Restore the system configuration from a given file", "filename", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_DYNAMIC, NULL, is_cli_dync_get_config_list, 2048, 0, 0},
{"configure configurations reset", "Reset the system to the default configuration", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure debug", "Debugging tokens", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, is_cli_cmd_debug_do, NULL, 0, 0, 3},
{"configure debug add", "Add the memory database node.", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure debug add path", "Path of memory database node", "/xx[/xx[/xx...]]", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure debug delete", "Delete the memory database node.", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure debug delete path", "Path of memory database node", "/xx[/xx[/xx...]]", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure debug modify", "Modify the memory database node.", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure debug modify path", "Path of memory database node", "/xx[/xx[/xx...]]", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure debug modify path new-value", "The new value string", "New value", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure debug query", "Query the memory database nodes.", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure debug query path", "Path of memory database node", "/xx[/xx[/xx...]]", NULL, NULL, TOKEN_MODE_OPTIONAL, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure debug query path child", "All children of the node", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure debug query path sub", "All offspring of the node", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure debug query path wild", "All matched offspring of the node", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure debug shell", "Go to local shell, only for debug.", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure dump", "Manage system dump files", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, is_cli_cmd_dump_mgmt, NULL, 0, 0, 0},
{"configure dump create", "Create a system dump file", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure dump create log", "Create a system log dump file as is_log_YYYYMMDDhhmmss", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure dump delete", "Delete a system dump file", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_DYNAMIC, NULL, is_cli_dync_get_dump_list, 2048, 0, 0},
{"configure exit", "Leave configuration mode", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, is_cli_cmd_config_exit, NULL, 0, 0, 0},
{"configure halt", "Shut down the system", "", NULL, NULL, TOKEN_MODE_OPTIONAL, TOKEN_TYPE_STATIC, is_cli_cmd_reload_go, NULL, 0, 0, 2},
{"configure halt noconfirm", "Shut down the system without asking about unsaved changes", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure help", "View description of the interactive help system", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, is_cli_cmd_help_do, NULL, 0, 0, 0},
{"configure images", "Manage local images", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, is_cli_cmd_image_config, NULL, 0, 0, 1},
{"configure images upload", "Upload an image file", "url such as http://xxx/file or scp://xxx@x.x.x.x:/path/file", NULL, NULL, TOKEN_MODE_OPTIONAL, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure images upload as", "Save the uploaded image file as the given name", "filename", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_DYNAMIC, NULL, is_cli_dync_get_image_list, 2048, 0, 0},
{"configure log", "Configure log", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, is_cli_cmd_misc_config, NULL, 0, 0, 0},
{"configure log level", "Configure system log level", "", "level", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure log level debug", "DEBUG", "", NULL, "7", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure log level info", "INFO", "", NULL, "6", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure log level notice", "NOTICE", "", NULL, "5", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure log level warn", "WARNING", "", NULL, "4", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure log level err", "ERROR", "", NULL, "3", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure log level crit", "CRITICAL", "", NULL, "2", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure log level alert", "ALERT", "", NULL, "1", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure log level emerg", "EMERGENCY", "", NULL, "0", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure log max-size", "Configure the max log file size", "1-10(MB)", "max-size", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure log reset", "Reset all system logs", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure log remote", "Configure remote log", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure log remote enable", "Enable remote log", "", "remote-enabled", "true", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure log remote server", "Add a remote log server", "hostname or IP address", NULL, NULL, TOKEN_MODE_OPTIONAL, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure log remote server port", "log server port, default 514", "port number", "port", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure login-banner", "Configure device login banner", "The new banner string, using '\\' as escape", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, is_cli_cmd_misc_config, NULL, 0, 0, 0},
{"configure management", "Management configuration", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, is_cli_cmd_mgmt_config, NULL, 0, 0, 0},
{"configure management eth-if", "Configure ethernet interface", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 2},
{"configure management eth-if enable", "Enable management interface", "", "state", "true", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure management eth-if ip", "Configure interface IP address", "IP address", "ip-address", NULL, TOKEN_MODE_OPTIONAL, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure management eth-if ip mask", "Configure interface IP net mask", "IP net mask", "ip-mask", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure management eth-if ip-mask", "Configure interface IP net mask", "IP net mask", "ip-mask", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure management eth-if ip-origin", "Configure interface IP origination", "", "ip-origin", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure management eth-if ip-origin static", "", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure management eth-if ip-origin dhcp", "", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure management eth-if default-gateway", "Configure default gateway for management interface", "IP address", "ip-default-gateway", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure management eth-if dhcp-sendname", "Configure sending hostname when DHCP", "", "dhcp-sendname", "true", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure management interface", "Configure ethernet interface", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_DYNAMIC, NULL, is_cli_dync_get_inf_list, 1024, 0, 1},
{"configure management interface device", "Add a VLAN interface on the net device", "", "dev", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_DYNAMIC, NULL, is_cli_dync_get_netdev_list, 1024, 0, 0},
{"configure management interface device vlan", "Configure interface VLAN ID", "2-4094", "vlan", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure management interface enable", "Enable ethernet interface", "", "state", "true", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure management interface desc", "Configure interface description", "string", "desc", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure management interface master", "Configure interface master device", "", "master", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_DYNAMIC, NULL, is_cli_dync_get_vrf_list, 1024, 0, 0},
{"configure management interface mtu", "Configure interface MTU size", "MTU size > 68", "mtu", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure management interface dhcp-sendname", "Configure sending hostname when DHCP", "", "dhcp-sendname", "true", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure management interface ipv4", "Configure interface IPV4 address", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure management interface ipv4 enable", "Enable IPV4", "", "ipv4-enabled", "true", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure management interface ipv4 static", "Enable IPV4 static address", "", "ipv4-origin", "static", TOKEN_MODE_OPTIONAL, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure management interface ipv4 static ip", "Configure IPV4 IP", "IPV4 address", "ipv4-address", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure management interface ipv4 static ip prefixlen", "Configure IPV4 prefix length", "0-32", "ipv4-prefix", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure management interface ipv4 ip", "Configure IPV4 IP", "IPV4 address", "ipv4-address", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure management interface ipv4 prefixlen", "Configure IPV4 prefix length", "0-32", "ipv4-prefix", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure management interface ipv4 dhcp", "Enable IPV4 DHCP", "", "ipv4-origin", "dhcp", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure management interface ipv6", "Configure interface IPV6 address", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure management interface ipv6 enable", "Enable IPV6", "", "ipv6-enabled", "true", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure management interface ipv6 static", "Enable IPV6 static address", "", "ipv6-origin", "static", TOKEN_MODE_OPTIONAL, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure management interface ipv6 static ip", "Configure IPV6 IP", "IPV6 address", "ipv6-address", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure management interface ipv6 static ip prefixlen", "Configure IPV6 prefix length", "0-128", "ipv6-prefix", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure management interface ipv6 ip", "Configure IPV6 IP", "IPV6 address", "ipv6-address", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure management interface ipv6 prefixlen", "Configure IPV6 prefix length", "0-128", "ipv6-prefix", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure management interface ipv6 dhcp", "Enable IPV6 DHCP", "", "ipv6-origin", "dhcp", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure management secondary-address", "Add a secondary address", "address name", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 1},
{"configure management secondary-address ip", "IP address", "IPV4/IPV6 address", "address", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure management secondary-address ip prefixlen", "IP address prefix length", "0-128", "prefix", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure management secondary-address ip prefixlen interface", "Interface name", "", "interface", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_DYNAMIC, NULL, is_cli_dync_get_inf_list, 1024, 0, 0},
{"configure management vrf", "Add a VRF routing table", "VRF name", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 1},
{"configure management vrf table", "VRF table ID", "number", "table", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure management vrf-process", "Add a VRF process", "VRF process binding name", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 1},
{"configure management vrf-process process", "process name", "", "process", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_DYNAMIC, NULL, is_cli_dync_get_net_process_list, 1024, 0, 0},
{"configure management vrf-process process vrf", "VRF name", "", "vrf", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_DYNAMIC, NULL, is_cli_dync_get_vrf_list, 1024, 0, 0},
{"configure management route", "Add an IP route, using '' for unused option", "route name", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 1},
{"configure management route dest", "Destination address", "ip subnet like 192.168.0.0/24", "dest", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure management route dest via", "Next hop address", "ip address", "via", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure management route dest via dev", "Routing device", "interface name", "dev", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_DYNAMIC, NULL, is_cli_dync_get_inf_list, 1024, 0, 0},
{"configure management route dest via dev metric", "Routing metric", "number", "metric", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure management route dest via dev metric table", "Route table ID", "number", "table", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure management default-gw", "Configure default gateway", "IP address", "default-gateway", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 1},
{"configure management dns", "Configure DNS server IP", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure management dns server", "Add a DNS server", "IP address", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure management permitted", "Configure management permitted IP", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 2},
{"configure management permitted enable", "Enable permitted IP check", "", "permit-enabled", "true", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure management permitted ip", "Add a permitted IP address", "IP address", NULL, NULL, TOKEN_MODE_OPTIONAL, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure management permitted ip mask", "Permitted IP net mask", "IP net mask", "mask", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure management whoami", "Turn on/off system OK led blink", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 2},
{"configure management whoami off", "Turn off system OK led blink", "", "enable", "false", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure management whoami on", "Turn off system OK led blink", "", "enable", "true", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure management ipsec", "Configure IPsec", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 1},
{"configure management ipsec enable", "Enable IPsec", "", "ipsec-enabled", "true", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure management ipsec connection", "Add/Modify an IPsec connection", "", NULL, NULL, TOKEN_MODE_OPTIONAL, TOKEN_TYPE_DYNAMIC, NULL, is_cli_dync_get_ipsec_conn, 1024, 0, 0},
{"configure management ipsec connection tries", "Attempts to negotiate", "a positive integer or %forever", "keyingtries", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure management ipsec connection ike", "IKE SA enc/auth algorithms", "encryption-integrity[-prf]-dhgroup", "ike", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure management ipsec connection esp", "ESP enc/auth algorithms", "encryption-integrity[-dhgroup][-esnmode]", "esp", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure management ipsec connection compress", "IPComp compression of content", "", "compress", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure management ipsec connection compress yes", "Turn on compression", "", NULL, "yes", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure management ipsec connection compress no", "Turn off compression", "", NULL, "no", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure management ipsec connection replay-window", "Replay window size", "-1|0|[size]", "replay-window", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure management ipsec connection dpdaction", "Controls the use of the Dead Peer Detection protocol", "", "dpdaction", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure management ipsec connection dpdaction none", "Disables the active sending of DPD messages", "", NULL, "none", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure management ipsec connection dpdaction clear", "The connection is closed", "", NULL, "clear", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure management ipsec connection dpdaction hold", "Re-negotiate the connection on demand", "", NULL, "hold", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure management ipsec connection dpdaction restart", "Re-negotiate the connection", "", NULL, "restart", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure management ipsec connection dpddelay", "The interval to send DPD messages", "0|[number]s", "dpddelay", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure management ipsec connection dpdtimeout", "The timeout interval to delete all connections to a peer in case of inactivity", "[number]s", "dpdtimeout", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure management ipsec connection ikelifetime", "How long the keying channel of a connection should last", "[number][s|m|h|d]", "ikelifetime", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure management ipsec connection lifetime", "How long a particular instance of a connection should last", "[number][s|m|h|d]", "lifetime", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure management ipsec connection local-ip", "Local IP", "IP/hostname/%any/%any6", "local-ip", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure management ipsec connection local-id", "Local authentication ID", "Authentication ID", "local-id", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure management ipsec connection local-id2", "Local additional authentication ID", "Authentication ID", "local-id2", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure management ipsec connection local-src", "Local virtual IP", "IP/%any/%config", "local-src", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure management ipsec connection local-sub", "Local private subnet", "IP subnet", "local-sub", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure management ipsec connection local-auth", "Local authentication methord", "", "local-auth", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_DYNAMIC, NULL, is_cli_dync_get_ipsec_auth_type, 1024, 0, 0},
{"configure management ipsec connection local-auth2", "Local additional authentication methord", "", "local-auth2", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_DYNAMIC, NULL, is_cli_dync_get_ipsec_auth_type, 1024, 0, 0},
{"configure management ipsec connection local-cert", "Local certificate", "", "local-cert", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_DYNAMIC, NULL, is_cli_dync_get_cert_list, 1024, 0, 0},
{"configure management ipsec connection local-cert2", "Local certificate", "", "local-cert2", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_DYNAMIC, NULL, is_cli_dync_get_cert_list, 1024, 0, 0},
{"configure management ipsec connection peer-ip", "Peer IP", "IP/hostname/%any/%any6", "peer-ip", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure management ipsec connection peer-id", "Peer authentication ID", "Authentication ID", "peer-id", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure management ipsec connection peer-id2", "Peer additional authentication ID", "Authentication ID", "peer-id2", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure management ipsec connection peer-src", "Peer virtual IP", "IP/%any/%config", "peer-src", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure management ipsec connection peer-sub", "Peer private subnet", "IP subnet", "peer-sub", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure management ipsec connection peer-auth", "Peer authentication methord", "", "peer-auth", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_DYNAMIC, NULL, is_cli_dync_get_ipsec_auth_type, 1024, 0, 0},
{"configure management ipsec connection peer-auth2", "Peer additional authentication methord", "", "peer-auth2", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_DYNAMIC, NULL, is_cli_dync_get_ipsec_auth_type, 1024, 0, 0},
{"configure management ipsec connection peer-cert", "Peer certificate", "", "peer-cert", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_DYNAMIC, NULL, is_cli_dync_get_cert_list, 1024, 0, 0},
{"configure management ipsec connection peer-cert2", "Peer certificate", "", "peer-cert2", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_DYNAMIC, NULL, is_cli_dync_get_cert_list, 1024, 0, 0},
{"configure management ipsec ca", "Add an IPsec Certification Authority", "ca name", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure management ipsec ca cacert", "The certificate", "", "cacert", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_DYNAMIC, NULL, is_cli_dync_get_cert_list, 1024, 0, 0},
{"configure management ipsec ca cacert ocspuri", "OCSP URI", "URI", "ocspuri", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure management ipsec secret", "Add an IPsec secret", "secret name", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure management ipsec secret psk", "Add a PSK secret", "", "type", "PSK", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure management ipsec secret psk key", "Pre-share key", "", "key-string", NULL, TOKEN_MODE_OPTIONAL, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure management ipsec secret psk key host", "Host ID", "IP/FQDN/user@FQDN/%any/%any6", "host", NULL, TOKEN_MODE_OPTIONAL, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure management ipsec secret psk key host peer", "Peer ID", "IP/FQDN/user@FQDN/%any/%any6", "peer", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure management ipsec secret eap", "Add an EAP credentials", "", "type", "EAP", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure management ipsec secret eap user", "EAP user ID", "user ID", "host", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure management ipsec secret eap user secret", "EAP secret", "secret", "key-string", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure management ipsec secret xauth", "Add an XAUTH credentials", "", "type", "XAUTH", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure management ipsec secret xauth user", "XAUTH user ID", "user ID", "host", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure management ipsec secret xauth user pass", "XAUTH password", "password", "key-string", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure management ipsec secret rsa", "Add an RSA key", "", "type", "RSA", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure management ipsec secret rsa key", "RSA private key", "key file", "key-file", NULL, TOKEN_MODE_OPTIONAL, TOKEN_TYPE_DYNAMIC, NULL, is_cli_dync_get_key_list, 1024, 0, 0},
{"configure management ipsec secret rsa key pass", "passphrase if the private key file is encrypted", "passphrase", "passphrase", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure management ipsec secret ecdsa", "Add an ECDSA key", "", "type", "ECDSA", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure management ipsec secret ecdsa key", "ECDSA private key", "key", "key-file", NULL, TOKEN_MODE_OPTIONAL, TOKEN_TYPE_DYNAMIC, NULL, is_cli_dync_get_key_list, 1024, 0, 0},
{"configure management ipsec secret ecdsa key pass", "passphrase if the private key file is encrypted", "passphrase", "passphrase", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure management ipsec secret type", "Add a Secret", "psk/eap/xauth/rsa/ecdsa", "type", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 3},
{"configure management ipsec secret type host", "Host user ID", "user ID", "host", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure management ipsec secret type host peer", "Peer user ID", "user ID", "peer", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure management ipsec secret type host peer key-string", "Key/secret/pass", "key text", "key-string", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure management ipsec secret type host peer key-string key-file", "Key/secret/pass", "key file", "key-file", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_DYNAMIC, NULL, is_cli_dync_get_key_list, 1024, 0, 0},
{"configure management ipsec secret type host peer key-string key-file pass", "passphrase if the key file is encrypted", "passphrase", "passphrase", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure management ipsec key", "Add a private key", "key identifier", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure management ipsec key file-url", "Upload a key file from an HTTP/HTTPS/SCP URL", "url such as http://xxx/file or scp://xxx@x.x.x.x:/path/file", "key-content", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure management ipsec key raw", "Add a key with raw content, using '\\' as escape", "key content", "key-content", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure management ipsec cert", "Add a certificate", "certificate identifier", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure management ipsec cert file-url", "Upload a certificate file from an HTTP/HTTPS/SCP URL", "url such as http://xxx/file or scp://xxx@x.x.x.x:/path/file", "cert-content", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure management ipsec cert raw", "Add a certificate with raw content, using '\\' as escape", "cert content", "cert-content", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure management iptables", "Add an iptbles rule", "iptbles rule name", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 1},
{"configure management iptables filter", "add a rule to filter table", "", "table", "filter", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure management iptables filter priority", "rule priority", "0 means the lowest priority", "priority", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure management iptables filter priority rule", "rule specification", "a quoted append/insert rule such as '-A INPUT -p tcp -j DROP'", "rule", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure management iptables filter priority rule ipv4", "IPv4 rule", "", "version", "ipv4", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure management iptables filter priority rule ipv6", "IPv6 rule", "", "version", "ipv6", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure name", "Configure device name, it will display in cli prompt", "hostname [a-zA-Z0-9-_.]", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, is_cli_cmd_misc_config, NULL, 0, 0, 0},
{"configure no", "Disable or remove certain configuration options", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, is_cli_cmd_no_do, NULL, 0, 0, 0},
{"configure no configuration", "Remove the system configuration", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_DYNAMIC, NULL, is_cli_dync_get_config_list, 2048, 0, 0},
{"configure no management", "Remove management configuration options", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure no management eth-if", "Configure ethernet interface", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 2},
{"configure no management eth-if enable", "Disable management interface", "", "state", "false", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure no management eth-if dhcp-sendname", "Disable sending hostname when DHCP", "", "dhcp-sendname", "false", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure no management dns", "Configure DNS server", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure no management dns server", "Remove management DNS server", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_DYNAMIC, NULL, is_cli_dync_get_mgmt_dns, 1024, 0, 0},
{"configure no management interface", "Configure or delete ethernet interface", "", NULL, NULL, TOKEN_MODE_OPTIONAL, TOKEN_TYPE_DYNAMIC, NULL, is_cli_dync_get_inf_list, 1024, 0, 1},
{"configure no management interface enable", "Disable ethernet interface", "", "state", "false", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure no management interface dhcp-sendname", "Disable sending hostname when DHCP", "", "dhcp-sendname", "false", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure no management interface master", "Remove the interface from master device", "", "master", "", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure no management interface ipv4", "Configure interface IPV4 address", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure no management interface ipv4 enable", "Disable IPV4", "", "ipv4-enabled", "false", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure no management interface ipv6", "Configure interface IPV6 address", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure no management interface ipv6 enable", "Disable IPV6", "", "ipv6-enabled", "false", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure no management secondary-address", "Remove a secondary address", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_DYNAMIC, NULL, is_cli_dync_get_addr_list, 1024, 0, 1},
{"configure no management ipsec", "Configure IPsec", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 1},
{"configure no management ipsec enable", "Disable IPsec", "", "ipsec-enabled", "false", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure no management ipsec connection", "Delete an IPsec connection", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_DYNAMIC, NULL, is_cli_dync_get_ipsec_conn, 1024, 0, 0},
{"configure no management ipsec secret", "Delete an IPsec secret", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_DYNAMIC, NULL, is_cli_dync_get_ipsec_secret, 1024, 0, 0},
{"configure no management ipsec key", "Delete a private key", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_DYNAMIC, NULL, is_cli_dync_get_key_list, 1024, 0, 0},
{"configure no management ipsec cert", "Delete a certificate", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_DYNAMIC, NULL, is_cli_dync_get_cert_list, 1024, 0, 0},
{"configure no management ipsec ca", "Delete an IPsec CA", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_DYNAMIC, NULL, is_cli_dync_get_ipsec_ca, 1024, 0, 0},
{"configure no management permitted", "Configure management permitted IP", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 2},
{"configure no management permitted enable", "Disable the permitted IP check", "", "permit-enabled", "false", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure no management permitted ip", "Remove management permitted IP", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_DYNAMIC, NULL, is_cli_dync_get_mgmt_permitted, 1024, 0, 2},
{"configure no management vrf", "Remove a VRF", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_DYNAMIC, NULL, is_cli_dync_get_vrf_list, 1024, 0, 1},
{"configure no management vrf-process", "Remove a VRF process", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_DYNAMIC, NULL, is_cli_dync_get_vrf_process_list, 1024, 0, 1},
{"configure no management route", "Remove a route", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_DYNAMIC, NULL, is_cli_dync_get_route_list, 1024, 0, 1},
{"configure no management iptables", "Remove an iptables rule", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_DYNAMIC, NULL, is_cli_dync_get_iptables_rule_list, 1024, 0, 1},
{"configure no log", "Configure log", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure no log remote", "Configure remote log", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure no log remote enable", "Disable remote log", "", "remote-enabled", "false", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure no log remote server", "Remove a log remote server", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_DYNAMIC, NULL, is_cli_dync_get_log_server, 1024, 0, 0},
{"configure no ntp", "Configure NTP", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure no ntp enable", "Disable NTP", "", "ntp-enabled", "false", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure no ntp server", "Remove a NTP server", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_DYNAMIC, NULL, is_cli_dync_get_ntp_server, 1024, 0, 0},
{"configure no snmp", "Remove a SNMP configuration", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure no snmp enable", "Disable SNMP server", "", "state", "false", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 2},
{"configure no snmp community", "Remove a SNMP community", "", NULL, NULL, TOKEN_MODE_OPTIONAL, TOKEN_TYPE_DYNAMIC, NULL, is_cli_dync_get_agent_commu, 1024, 0, 2},
{"configure no snmp community enable", "Disable this community(need apply)", "", "state", "false", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure no snmp host", "Remove a SNMP trap host", "", NULL, NULL, TOKEN_MODE_OPTIONAL, TOKEN_TYPE_DYNAMIC, NULL, is_cli_dync_get_trap_host, 1024, 0, 0},
{"configure no snmp host enable", "Disable send trap to this host(need apply)", "", "state", "false", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure no snmp user", "Remove a SNMP trap user", "", NULL, NULL, TOKEN_MODE_OPTIONAL, TOKEN_TYPE_DYNAMIC, NULL, is_cli_dync_get_agent_user, 1024, 0, 2},
{"configure no snmp user enable", "Disable this user(need apply)", "", "state", "false", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure no snmp trap", "SNMP trap send control", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 2},
{"configure no snmp trap all", "Disable all trap", "", "all", "false", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure no snmp trap application", "Disable application trap", "", "application", "false", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure no snmp trap fan", "Disable fan trap", "", "fan", "false", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure no snmp trap power", "Disable power trap", "", "power", "false", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure no snmp trap sensor", "Disable sensor trap", "", "sensor", "false", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure no snmp trap switch", "Disable switch trap", "", "switch", "false", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure no snmp trap system", "Disable system trap", "", "system", "false", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure no snmp trap threshold", "Disable threshold trap", "", "threshold", "false", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure no snmp trap terminal", "Disable terminal trap", "", "terminal", "false", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure no snmp trap app-fail", "Disable application failure trap", "", "app-fail", "false", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure no snmp trap bypass", "Disable Bypass trap", "", "bypass", "false", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure no snmp trap mon-link", "Disable monitor port link trap", "", "mon-link", "false", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure no snmp trap net-link", "Disable net port link trap", "", "net-link", "false", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure no snmp trap error", "Disable error trap", "", "error", "false", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure no ssh", "Configure ssh service", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 3},
{"configure no ssh enable", "Disable ssh service", "", "enabled", "false", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure no radius", "Configure RADIUS login", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure no radius enable", "Disable RADIUS login", "", "enabled", "false", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure no radius local-login", "Disable allowing local users login", "", "fallback", "false", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure no radius server", "Remove a RADIUS server", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_DYNAMIC, NULL, is_cli_dync_get_radius_srv, 1024, 0, 0},
{"configure no tacacs", "Configure TACACS+ login", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure no tacacs enable", "Disable TACACS+ login", "", "enabled", "false", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure no tacacs local-login", "Disable allowing local users login", "", "fallback", "false", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure no tacacs server", "Remove a TACACS+ server", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_DYNAMIC, NULL, is_cli_dync_get_tacacs_srv, 1024, 0, 0},
{"configure no user", "Configure local login", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure no user name", "Remove a local user account", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_DYNAMIC, NULL, is_cli_dync_get_user_account, 1024, 0, 0},
{"configure no web", "Configure web service", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure no web http", "Configure HTTP service", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure no web http enable", "Disable HTTP service", "", "enabled", "false", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure no web https", "Configure HTTPS service", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure no web https enable", "Disable HTTPS service", "", "enabled", "false", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure ntp", "Configure NTP", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, is_cli_cmd_ntp_config, NULL, 0, 0, 0},
{"configure ntp enable", "Enable NTP", "", "ntp-enabled", "true", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure ntp server", "Add an NTP server", "hostname or IP address", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure radius", "Configure RADIUS login", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, is_cli_cmd_aaa_config, NULL, 0, 0, 0},
{"configure radius enable", "Enable RADIUS login", "", "enabled", "true", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure radius local-login", "Configure RADIUS the allow local users login", "", "fallback", "true", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure radius privilege", "Configure RADIUS user privilege", "", "privilege", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure radius privilege readonly", "Readonly access", "", NULL, "1", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure radius privilege normal", "Normal read and write", "", NULL, "2", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure radius privilege admin", "Administrator", "", NULL, "3", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure radius retry", "Configure RADIUS login retry count", "Number of retry", "retry", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure radius server", "Add a RADIUS server", "ID number", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure radius server ip", "RADIUS server IP", "IP address", "server-ip", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure radius server ip port", "RADIUS server port", "port number", "server-port", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure radius server ip port secret", "Server secret", "secret string", "secret", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure radius server ip port secret timeout", "Timeout", "1-60 seconds", "timeout", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure reload", "Reboot the system", "", NULL, NULL, TOKEN_MODE_OPTIONAL, TOKEN_TYPE_STATIC, is_cli_cmd_reload_go, NULL, 0, 0, 0},
{"configure reload switch-software", "Reboot the system and Switch current firmware and backup software", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure reload force", "Force an immediate reboot of the system even if it's busy", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure reload noconfirm", "Reboot the system without asking about unsaved changes", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure reset", "Reset the system to factory setting", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, is_cli_cmd_reload_go, NULL, 0, 0, 0},
{"configure session", "Configure or close session", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, is_cli_cmd_session_config, NULL, 0, 0, 0},
{"configure session expired-time", "Configure CLI session expired time", "in seconds, 0 means disable", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure show", "Display system configuration or statistics", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, is_cli_cmd_show_do, NULL, 0, 0, 0},
{"configure show cli", "Display CLI options", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure show clock", "Display system time and date", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure show com", "Display serial console configuration", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure show com configured", "Display serial console configuration", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure show configurations", "Display the system configurations", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure show configurations list", "Display the system configuration file list", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure show configurations detail", "Display the system configuration in detail", "filename ", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_DYNAMIC, NULL, is_cli_dync_get_config_list, 2048, 0, 0},
{"configure show cpu", "Display CPU usage", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure show dump", "Display system dump file list", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure show event", "Display system events", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure show images", "Display local images", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 1},
{"configure show log", "Display log or its configuration", "", NULL, NULL, TOKEN_MODE_OPTIONAL, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure show log filter", "Display log with filter", "filter keyword", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure show log realtime", "Display realtime log", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure show log configured", "Display log configuration", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure show login-banner", "Display device logine banner configuration", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure show login-banner configured", "Display device logine banner configuration", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure show management", "Display system management configuration and state", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure show management configured", "Display system management configuration", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure show management state", "Display system management state", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure show memory", "Display system memory usage", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure show name", "Display device name configuration", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure show name configured", "Display device name configuration", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure show ntp", "Display NTP runtime state", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure show ntp configured", "Display NTP configuration", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure show radius", "Display RADIUS configuration", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure show radius configured", "Display RADIUS configuration", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure show running-config", "Display running configuration", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure show session", "Display session runtime state", "", NULL, NULL, TOKEN_MODE_OPTIONAL, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure show session configured", "Display session configuration", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure show snmp", "Display SNMP runtime state", "", NULL, NULL, TOKEN_MODE_OPTIONAL, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure show snmp configured", "Display SNMP configuration", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure show snmp engineID", "Display SNMP engine ID of the local system", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure show ssh", "Display SSH runtime state", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure show ssh configured", "Display SSH configuration", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure show storage", "Display storage usage", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure show tacacs", "Display TACACS+ configuration", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure show tacacs configured", "Display TACACS+ configuration", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure show upgrade", "Display upgrade information", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure show upgrade state", "Display current upgrade state", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure show uptime", "Display system uptime info", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure show users", "Display a list of user accounts", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure show version", "Display version information for current system image", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure show web", "Display web runtime state", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure show web configured", "Display web configuration", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure snmp", "Configure SNMP", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, is_cli_cmd_snmp_config, NULL, 0, 0, 0},
{"configure snmp apply", "Apply SNMP configuration", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure snmp community", "Add or configure a SNMP v1/v2c community(need apply)", "5-31 characters", NULL, NULL, TOKEN_MODE_OPTIONAL, TOKEN_TYPE_DYNAMIC, NULL, is_cli_dync_get_agent_commu, 1024, 0, 2},
{"configure snmp community enable", "Enable user(need apply)", "", "state", "true", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure snmp community full-access", "Set full access(need apply)", "", "full-access", "true", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure snmp community read-only", "Set read only(need apply)", "", "full-access", "false", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure snmp enable", "Enable SNMP server", "", "state", "true", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 2},
{"configure snmp host", "Configure a host which to send SNMP traps to(need apply)", "host IP address", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_DYNAMIC, NULL, is_cli_dync_get_trap_host, 1024, 0, 0},
{"configure snmp host enable", "Enable send trap to this host(need apply)", "", "state", "true", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure snmp host v1", "Add SNMP Version 1 trap host", "", "version", "v1", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure snmp host v1 community", "SNMP community", "community string", "community", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure snmp host v2c", "Add SNMP Version 2c trap host", "", "version", "v2c", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure snmp host v2c community", "SNMP community", "community string", "community", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure snmp host v3", "Add SNMP Version 3 trap host", "", "version", "v3", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure snmp host v3 user", "Set access user", "user name", "community", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure snmp host v3 user password", "Set access user password", "password", "password", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure snmp host v3 user password md5", "Use the MD5 hash algorithm", "", "auth", "md5", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure snmp host v3 user password sha", "Use the SHA1 hash algorithm", "", "auth", "sha", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure snmp threshold", "Configure threshold for SNMP trap", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 2},
{"configure snmp threshold fan", "Configure fan threshold", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure snmp threshold fan min", "Configure minimal fan speed", "fan speed, 100-10000 RPM", "min", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure snmp threshold fan max", "Configure maximal fan speed", "fan speed, 10000-40000 RPM", "max", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure snmp threshold sensor", "Configure sensor threshold", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure snmp threshold sensor bcm-max", "Configure bcm sensor max temperature", "max temperature for sensor warning, 60-90 °C", "bcm-max", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure snmp threshold sensor switch-max", "Configure switch sensor max temperature", "max temperature for sensor warning, 60-90 °C", "switch-max", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure snmp threshold sensor module-max", "Configure module sensor max temperature", "max temperature for sensor warning, 60-90 °C", "module-max", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure snmp threshold sensor port-max", "Configure port sensor max temperature", "max temperature for sensor warning, 60-90 °C", "port-max", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure snmp trap", "SNMP trap send control", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 2},
{"configure snmp trap all", "Enable all trap", "", "all", "true", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure snmp trap application", "Enable application trap", "", "application", "true", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure snmp trap fan", "Enable fan trap", "", "fan", "true", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure snmp trap power", "Enable power trap", "", "power", "true", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure snmp trap sensor", "Enable sensor trap", "", "sensor", "true", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure snmp trap switch", "Enable switch trap", "", "switch", "true", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure snmp trap system", "Enable system trap", "", "system", "true", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure snmp trap threshold", "Enable threshold trap", "", "threshold", "true", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure snmp trap terminal", "Enable terminal trap", "", "terminal", "true", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure snmp trap app-fail", "Enable application failure trap", "", "app-fail", "true", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure snmp trap bypass", "Enable Bypass trap", "", "bypass", "true", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure snmp trap mon-link", "Enable monitor port link trap", "", "mon-link", "true", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure snmp trap net-link", "Enable net port link trap", "", "net-link", "true", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure snmp trap error", "Enable error trap", "", "error", "true", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure snmp user", "Configure a SNMP v3 access user(need apply)", "5-31 characters", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_DYNAMIC, NULL, is_cli_dync_get_agent_user, 1024, 0, 2},
{"configure snmp user password", "Add a SNMP v3 user", "minimum 8 characters", "password", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure snmp user password md5", "Use the MD5 hash algorithm", "", "auth", "md5", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure snmp user password sha", "Use the SHA1 hash algorithm", "", "auth", "sha", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure snmp user enable", "Enable this user(need apply)", "", "state", "true", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure snmp user full-access", "Add full access(need apply)", "", "full-access", "true", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure snmp user read-only", "Add read only(need apply)", "", "full-access", "false", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure ssh", "Configure ssh service", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, is_cli_cmd_service_config, NULL, 0, 0, 0},
{"configure ssh enable", "Enable ssh service", "", "enabled", "true", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure ssh port", "Configure ssh service port", "port number, default 22", "port", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure ssh host-key", "Configure ssh host keys", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure ssh host-key remove", "Remove all keys belonging to hostname", "IP address or hostname", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure tacacs", "Configure TACACS+ login", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, is_cli_cmd_aaa_config, NULL, 0, 0, 0},
{"configure tacacs enable", "Enable TACACS+ login", "", "enabled", "true", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure tacacs local-login", "Configure TACACS+ allow local users login", "", "fallback", "true", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure tacacs service", "Set TACACS+ service Tag", "tag except slip/ppp/arap/shell/tty-daemon/connection/system/firewall", "service", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure tacacs timeout", "Set TACACS+ timeout", "1-60 seconds", "timeout", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure tacacs server", "Add a TACACS+ server", "ID number", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure tacacs server ip", "Add a TACACS+ server IP", "IP address", "server-ip", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure tacacs server ip port", "TACACS+ server port", "port number", "server-port", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure tacacs server ip port secret", "Server secret", "secret string", "secret", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},

{"configure upgrade", "Upgrade system", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, is_cli_cmd_upgrade_do, NULL, 0, 0, 0},
{"configure upgrade file-url", "Upgrade with an image from an HTTP/HTTPS/SCP/FTP URL", "url such as http://xxx/file or scp://xxx@x.x.x.x:/path/file", NULL, NULL, TOKEN_MODE_OPTIONAL, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure upgrade file-url ftp-user", "FTP user name", "user name", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure upgrade file-url ftp-user ftp-password", "FTP user password", "plain text", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure upgrade manufacture", "Manufacture mode upgrade", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 3},
{"configure upgrade manufacture file-url", "Upgrade with an upgrade image from an HTTP/HTTPS/SCP/FTP URL", "url such as http://xxx/file or scp://xxx@x.x.x.x:/path/file", NULL, NULL, TOKEN_MODE_OPTIONAL, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure upgrade manufacture file-url ftp-user", "FTP user name", "user name", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure upgrade manufacture file-url ftp-user ftp-password", "FTP user password", "plain text", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure upgrade image", "Upgrade with a local image", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_DYNAMIC, NULL, is_cli_dync_get_image_list, 2048, 0, 1},
{"configure user", "Configure local user account", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, is_cli_cmd_aaa_config, NULL, 0, 0, 0},
{"configure user change-password", "Change local user password", "", NULL, NULL, TOKEN_MODE_OPTIONAL, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure user change-password new-password", "Change the login user password with plain text", "maximum 40 characters", NULL, NULL, TOKEN_MODE_OPTIONAL, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure user change-password new-password user-name", "Change the given user password with plain text", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_DYNAMIC, NULL, is_cli_dync_get_user_account, 1024, 0, 0},
{"configure user change-password new-encrypt-password", "Change the login user password with encrypted string", "encrypted string", "shadow", NULL, TOKEN_MODE_OPTIONAL, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure user change-password new-encrypt-password user-name", "Change the given user password with encrypted string", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_DYNAMIC, NULL, is_cli_dync_get_user_account, 1024, 0, 0},
{"configure user name", "Add a local user", "maximum 31 characters", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure user name full-name", "User full name", "User description", "full-name", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure user name full-name password", "User password in plain text", "maximum 40 characters", "passwd", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure user name full-name password privilege", "User privilege", "", "privilege", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure user name full-name password privilege readonly", "Only read right", "", NULL, "1", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure user name full-name password privilege normal", "Normal read and write", "", NULL, "2", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure user name full-name password privilege admin", "Administrator", "", NULL, "3", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure user name full-name encrypt-password", "Add a local user with encrypted password", "encrypted string", "shadow", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure user name full-name encrypt-password privilege", "User privilege", "", "privilege", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure user name full-name encrypt-password privilege readonly", "Only read right", "", NULL, "1", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure user name full-name encrypt-password privilege normal", "Normal read and write", "", NULL, "2", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure user name full-name encrypt-password privilege admin", "Administrator", "", NULL, "3", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure web", "Configure web service", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, is_cli_cmd_service_config, NULL, 0, 0, 0},
{"configure web session-expired-time", "Configure web session expired time", "minimal 60 seconds", "session-timeout", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure web http", "Configure HTTP service", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure web http enable", "Enable HTTP service", "", "enabled", "true", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure web http port", "Configure HTTP listenning port", "port number, default 80", "port", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure web https", "Configure HTTPS service", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure web https enable", "Enable HTTPS service", "", "enabled", "true", TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure web https port", "Configure HTTPS listenning port", "port number, default 443", "port", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure web https ssl", "Configure the SSL certificate and key file", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure web https ssl cert", "The SSL certificate", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure web https ssl cert file-url", "Upload an SSL certificate from an HTTP/HTTPS/SCP URL", "url such as http://xxx/file or scp://xxx@x.x.x.x:/path/file", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure web https ssl cert raw", "Configure the SSL certificate with raw content, using '\\' as escape", "raw string", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure web https ssl key", "The SSL key", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
{"configure web https ssl key file-url", "Upload an SSL key file from an HTTP/HTTPS/SCP URL", "url such as http://xxx/file or scp://xxx@x.x.x.x:/path/file", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure web https ssl key raw", "Configure the SSL key with raw content, using '\\' as escape", "raw string", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_VARIABLE, NULL, NULL, 0, 0, 0},
{"configure shellcmd", "Execute selected shell program directly", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, is_cli_cmd_shellcmd_do, NULL, 0, 0, 1},
{"configure shellcmd dhclient", "Execute the dhclient command", "command arguments", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_COMMAND, NULL, NULL, 0, 0, 0},
{"configure shellcmd dmesg", "Execute the dmesg command", "command arguments", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_COMMAND, NULL, NULL, 0, 0, 0},
{"configure shellcmd ethtool", "Execute the ethtool command", "command arguments", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_COMMAND, NULL, NULL, 0, 0, 0},
{"configure shellcmd ip", "Execute the ip command", "command arguments", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_COMMAND, NULL, NULL, 0, 0, 0},
{"configure shellcmd ifconfig", "Execute the ifconfig command", "command arguments", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_COMMAND, NULL, NULL, 0, 0, 0},
{"configure shellcmd openssl", "Execute the openssl command", "command arguments", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_COMMAND, NULL, NULL, 0, 0, 0},
{"configure shellcmd ping", "Execute the ping command", "command arguments", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_COMMAND, NULL, NULL, 0, 0, 0},
{"configure shellcmd traceroute", "Execute the traceroute command", "command arguments", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_COMMAND, NULL, NULL, 0, 0, 0},
{"configure shellcmd vconfig", "Execute the vconfig command", "command arguments", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_COMMAND, NULL, NULL, 0, 0, 0},
{"configure write", "Save the running configuration to persistent storage", "", NULL, NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, is_cli_cmd_write_go, NULL, 0, 0, 0},
{"configure write memory", "Save running configuration to the active configuration file", "", "save-config", NULL, TOKEN_MODE_SINGLE, TOKEN_TYPE_STATIC, NULL, NULL, 0, 0, 0},
};

#define PRODUCT_LIB		"/usr/lib/libprod_cli_inst.so"

static silc_cli_product_info* load_product_info()
{
	struct stat fs;
	void *dl_handle;
	char *filename = PRODUCT_LIB;
	silc_cli_get_product_info_func get_product_info_func;
	silc_cli_product_info* product_info = NULL;

	if ((stat(filename, &fs)) != 0 || !(fs.st_mode & S_IFREG))
	{
		printf("%s: File does not exist.\n", filename);
		return NULL;
	}

	if ((dl_handle = dlopen(filename, RTLD_NOW)) == NULL)
	{
		printf("%s: dlopen %s\n", filename, dlerror());
		return NULL;
	}

	get_product_info_func = dlsym(dl_handle, "cli_get_product_info");
	if (get_product_info_func == NULL)
	{
		printf("%s: dlsym %s\n", filename, dlerror());
		dlclose(dl_handle);
		return NULL;
	}
	product_info = get_product_info_func();
	if (product_info == NULL)
	{
		printf("Fail to get product info\n");
		dlclose(dl_handle);
		return NULL;
	}
	silc_mgmtd_if_product_info_set(product_info->product_name,
			product_info->product_id,
			product_info->vendor_list,
			product_info->vendor_cnt);

	return product_info;
}


silc_cli_product_info* g_cli_product_info = NULL;
silc_cli_product_info* silc_cli_get_product_info(void)
{
	return g_cli_product_info;
}

int is_cli_init()
{
    int loop;
    silc_cli_mode_info* p_mode;

    g_cli_product_info = load_product_info();

    // init mode
    silc_cli_mode_list_init();
    for(loop=0; loop<sizeof(s_silc_cli_mode_info_list)/sizeof(silc_cli_mode_info); loop++)
    {
        p_mode = &s_silc_cli_mode_info_list[loop];
        if(silc_cli_mode_add(p_mode->name, p_mode->prompt) < 0)
            return -1;
    }

    // init token
    for(loop=0; loop<sizeof(s_silc_cli_token_info_list)/sizeof(silc_cli_token_info); loop++)
    {
        if(silc_cli_token_add(&s_silc_cli_token_info_list[loop]) < 0)
            return -1;
    }

    if(g_cli_product_info)
    {
    	silc_cli_token_info* token_info_list = g_cli_product_info->token_list;
    	int token_info_cnt = g_cli_product_info->token_cnt;

		for(loop=0; loop<token_info_cnt; loop++)
		{
			if(silc_cli_token_add(&token_info_list[loop]) < 0)
				return -1;
		}
    }

    return is_cli_user_init(); 
}
